# Generated by Django 5.0.7 on 2024-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('for_rent', 'For Rent'), ('for_sale', 'For Sale')], default='for_sale', max_length=50),
        ),
    ]
